#!/bin/bash

# By Rainman
# V20243010
# 0.0.5.9

# what's the purpose of this tool?
# this tool introduce helping functions and features for admins running a wow server.

# how do you get it to work?

# re/install
if [[ ! -f /usr/local/bin/mangos ]] &>/dev/null; then
  clear
  printf "Install CMaNGOS-Script? y/n "
  read -r -p "" -n 1 -r -s
  if [[ $REPLY =~ ^[Yy]$ ]] &>/dev/null; then
    sudo rm /usr/local/bin/mango &>/dev/null
  fi
fi

# if missing
if [[ ! -f /usr/local/bin/mangos ]] &>/dev/null; then
  # first time install
  echo "Creating /home directory.."
  sudo mkdir /home/"$(whoami)" &>/dev/null

  # fix cmangos-script ownership
  sudo chown -R "$(whoami)":"$(groups 2>&1 | awk '{ print $1 }' 2>&1)" /home/

  if [[ ! -f /home/cmangos-script/README.md ]] &>/dev/null; then
    echo "Cloning repo.."
    cd /home/"$(whoami)" || exit && git clone https://github.com/Daedalus-code/cmangos-script.git
  fi

  echo "Installing script (mangos).."
  sudo cp /home/"$(whoami)"/cmangos-script/mangos /usr/local/bin
  echo "Making script executable.."
  sudo chmod +x /usr/local/bin/mangos

  # mangos script will look for config files inside your "install folder" (default: /home)
  # you need to copy config files from cmangos-script folder into your "install folder".

  if [[ ! -f /home/server.cnf ]] &>/dev/null; then
    echo "Copying configuration.."
    cp /home/"$(whoami)"/cmangos-script/server.cnf /home/
    echo "edit config file 'server.cnf' with MySQL credentials."
    echo
    echo "(nano) Save with CTRL+o"
    read -r -p "Press Enter to continue" </dev/tty
    nano /home/server.cnf
  fi
  echo
  if [[ ! -f /home/server.txt ]] &>/dev/null; then
    echo "Copying configuration.."
    cp /home/"$(whoami)"/cmangos-script/server.txt /home/
    echo "edit config file 'server.txt' with correct information."
    echo
    echo "(nano) Save with CTRL+o"
    read -r -p "Press Enter to continue" </dev/tty
    nano /home/server.txt
  fi
  echo "[OK] 'mangos' installed!!"
  echo "Type 'mangos' to start."
else
  echo "[OK] 'mangos' already installed!"
  echo "Type 'mangos' to start."
fi

# END
