#!/bin/bash

# By Rainman
# V20251101
# 2.3.4.3

################################################################################

# install
if [[ -f /usr/local/bin/mangos ]] &>/dev/null; then
  clear
  printf "[!?] Install CMaNGOS-Script? y/n "
  read -r -p "" -n 1 -r -s
  if [[ $REPLY =~ ^[Yy]$ ]] &>/dev/null; then
    sudo rm /usr/local/bin/mangos &>/dev/null
  fi
fi

################################################################################

# re/install
if [[ ! -f /usr/local/bin/mangos ]] &>/dev/null; then

  ##############################################################################

  clear
  # first time install
  echo "[!!] Creating /home directory.."
  sudo mkdir /home/"$(whoami)" &>/dev/null

  ##############################################################################

  # fix cmangos-script ownership
  sudo chown -R "$(whoami)":"$(groups 2>&1 | awk '{ print $1 }' 2>&1)" /home/

  ##############################################################################

  if [[ ! -f /home/cmangos-script/README.md ]] &>/dev/null; then
    echo "[++] Cloning repo.."
    cd /home/"$(whoami)" || exit && git clone https://github.com/Daedalus-code/cmangos-script.git 2>/dev/null
  fi

  ##############################################################################

  echo "[!!] Installing script (mangos).."
  sudo cp /home/"$(whoami)"/cmangos-script/mangos /usr/local/bin
  echo "[-x] Making script executable.."
  sudo chmod +x /usr/local/bin/mangos

  ##############################################################################

  # install new configuration
  cp /home/"$(whoami)"/cmangos-script/server.cnf /home/
  # edit server configuration
  read -r -p "Press Enter to edit mysql configuration" </dev/tty
  nano /home/server.cnf
  echo "[OK] Copying new server configuration.."

  ##############################################################################

  # install new mysql configuration
  cp /home/"$(whoami)"/cmangos-script/server.txt /home/
  # edit mysql configuration
  read -r -p "Press Enter to edit server configuration" </dev/tty
  nano /home/server.txt
  echo "[OK] Copying new mysql configuration.."

  ##############################################################################

  # install output
  echo "[OK] 'mangos' installed!!"
  echo "[OK] Type 'mangos' to start."
fi

# END
