#!/bin/bash

source /home/server.txt

# get date
NOW="$(date +"%m.%d.%Y")"

# are we locked out?
FILE="${FOLDER_WOW:?}/lock"
if [ ! -f "$FILE" ]; then

  # running latest? NOTE: makes more sense for a PTR Server (Public Test Realm)
  # CMaNGOS Core #################### mangos-classic updates ###################

  ###########################
  # Checking latest release #
  ###########################
  cd "${FOLDER_CORE:?}" || exit
  if git checkout master &>/dev/null &&
    git fetch origin master &>/dev/null &&
    [ "$(git rev-list HEAD...origin/master --count)" != 0 ] &&
    git merge origin/master; then
    # create a lock file
    touch "$FOLDER_WOW"/lock &>/dev/null
    # update system
    sudo apt-get update &>/dev/null
    #####################
    # Stopping services #
    #####################
    # service status
    REALM_SERVICE=realmd
    WORLD_SERVICE=mangosd
    # realmd service
    case "$(pidof $REALM_SERVICE |
      wc -w)" in
    # not running, do nothing
    0) ;;
    # running, do shutdown
    *) sudo service realmd stop ;;
    esac
    # mangosd service
    case "$(pidof $WORLD_SERVICE |
      wc -w)" in
    # not running, do nothing
    0) ;;
    # running, do shutdown
    *) sudo service mangosd stop ;;
    esac
    ########################
    # moving logs, configs #
    ########################
    # fix directory permissions
    sudo chown -R "${USER:?}":"${GROUP:?}" "$FOLDER_WOW"
    # create new server.log
    touch "$FOLDER_CORE"/run/logs/Server.log &>/dev/null
    # copy all logs into 'old' folder
    cp "$FOLDER_CORE"/run/logs/*.log "$FOLDER_CORE"/run/logs/old
    # ahbot.conf
    cp "$FOLDER_CORE"/src/game/AuctionHouseBot/ahbot.conf.dist.in "$FOLDER_CORE"/run/etc/ahbot.conf.dist &>/dev/null
    # new compile, new system logs
    cd "$FOLDER_CORE"/run/logs || exit &>/dev/null
    mv -t "$FOLDER_CORE"/run/logs/old/ Realmd.log Server.log Server.log.old DBErrors.log EventAIErrors.log &>/dev/null
    # fix directory permissions
    sudo chown -R "$USER":"$GROUP" "$FOLDER_WOW"
    ###################
    # Building server #
    ###################
    # make sure 'build' folder exist
    mkdir "$FOLDER_CORE"/build &>/dev/null
    cd "${FOLDER_BUILD:?}" || exit
    # double quotes ("") and single quotes ('') around > $cmake < will mess things up.
    # shellcheck disable=SC2086
    cmake .. ${CMAKE:?}
    cd "$FOLDER_BUILD" || exit
    make -j3 # WARNING USING 3 CORES SETTING ! (raspberry pi4 setting)
    sudo make install &>/dev/null
    sudo chown -R "$USER":"$GROUP" "$FOLDER_WOW"
    # delete lock file
    sudo rm "$FOLDER_WOW"/lock &>/dev/null
  else
    # already updated
    echo "OK"
  fi

  # CMaNGOS Database #################### classic-db updates ###################

  ###########################
  # Checking latest release #
  ###########################
  # CMaNGOS Core (mangos-classic)
  cd "${FOLDER_DB:?}" || exit
  if git checkout master &>/dev/null &&
    git fetch origin master &>/dev/null &&
    [ "$(git rev-list HEAD...origin/master --count)" != 0 ] &&
    git merge origin/master; then
    # create a lock file
    touch "$FOLDER_WOW"/lock &>/dev/null
    # update system
    sudo apt-get update &>/dev/null
    #####################
    # Stopping services #
    #####################
    # service status
    REALM_SERVICE=realmd
    WORLD_SERVICE=mangosd
    # realmd service
    case "$(pidof $REALM_SERVICE |
      wc -w)" in
    # not running, do nothing
    0) ;;
    # running, do shutdown
    *) sudo service realmd stop ;;
    esac
    # mangosd service
    case "$(pidof $WORLD_SERVICE |
      wc -w)" in
    # not running, do nothing
    0) ;;
    # running, do shutdown
    *) sudo service mangosd stop ;;
    esac
    ########################
    # Moving logs, configs #
    ########################
    # fix directory permissions
    sudo chown -R "$USER":"$GROUP" "$FOLDER_WOW"
    # backup
    # make sure 'backup' folder exist
    mkdir "$FOLDER_WOW"/backup &>/dev/null
    # make sure 'old' folder exist
    mkdir "$FOLDER_WOW"/backup/old &>/dev/null
    # move all sql files inside backup into 'old' folder
    cp "$FOLDER_WOW"/backup/*.sql "$FOLDER_WOW"/backup/old &>/dev/null
    cd "$FOLDER_WOW"/backup/old/ || exit
    # zip all sql files inside backup
    zip "${server_name:?}.zip" "$FOLDER_WOW"/backup/*.sql &>/dev/null
    # remove old backup inside 'backup' folder (older than 7 days)
    find "$FOLDER_WOW"/backup/*.sql -mtime +7 -exec rm {} \; &>/dev/null
    # remove old backup inside 'old' folder (older than 14 days)
    find "$FOLDER_WOW"/backup/old/*.sql -mtime +14 -exec rm {} \; &>/dev/null
    ################
    # MySQL backup #
    ################
    # backup <- characters.sql
    mysqldump --defaults-extra-file="${SQL_MYCNF:?}" "$DB_CHARACTERS" >"$FOLDER_WOW"/backup/"${DB_CHARACTERS:?}"-"$NOW".sql
    # backup <- realmd.sql
    mysqldump --defaults-extra-file="$SQL_MYCNF" "$DB_REALMD" >"$FOLDER_WOW"/backup/"${DB_REALMD:?}"-"$NOW".sql
    #############
    # sql fixes #
    #############
    # fix directory permissions
    sudo chown -R "$USER":"$GROUP" "$FOLDER_WOW"
    # combine [A] to [B] updates individually
    # combine all characters updates
    cat "${FOLDER_CORE:?}"/sql/updates/characters/*.sql >"$FOLDER_WOW"/.all_characters.sql
    # combine all mangos updates
    cat "${FOLDER_CORE:?}"/sql/updates/mangos/*.sql >"$FOLDER_WOW"/.all_mangos.sql
    # combine all realmd updates
    cat "${FOLDER_CORE:?}"/sql/updates/realmd/*.sql >"$FOLDER_WOW"/.all_realmd.sql
    # do the actual fixes to the database server
    # update characters database
    mysql --defaults-extra-file="$SQL_MYCNF" -f --database="$DB_CHARACTERS" <"$FOLDER_WOW"/.all_characters.sql 2>/dev/null
    # update mangos database
    mysql --defaults-extra-file="$SQL_MYCNF" -f --database="${DB_MANGOS:?}" <"$FOLDER_WOW"/.all_mangos.sql 2>/dev/null
    # update realmd database
    mysql --defaults-extra-file="$SQL_MYCNF" -f --database="$DB_REALMD" <"$FOLDER_WOW"/.all_realmd.sql 2>/dev/null
    # remove old combined updates sql files
    rm "$FOLDER_WOW"/.*.sql 2>/dev/null
    #########################
    # Install full database #
    #########################
    # InstallFullDB
    cd "$FOLDER_DB" || exit
    ./InstallFullDB.sh
    # delete lock file
    sudo rm "$FOLDER_WOW"/lock &>/dev/null
  else
    # already updated
    echo "OK"
  fi

  # is it running? ################## realmd ###################################

  # service running? >
  if sudo service realmd status &>/dev/null; then
    # running
    echo "OK"
  else
    # offline
    sudo service realmd restart &>/dev/null
  fi

  # is it connected? ################ realmd ###################################

  # realmd mysql gone away >
  if tail "$FOLDER_CORE"/run/logs/Realmd.log 2>/dev/null |
    grep -m 1 "gone away" 2>/dev/null; then
    # it's gone..
    sudo service realmd restart
  else
    # running
    echo "OK"
  fi
  # realmd mysql connection was killed >
  if tail "$FOLDER_CORE"/run/logs/Realmd.log 2>/dev/null |
    grep -m 1 "Connection was killed" 2>/dev/null; then
    # it's gone..
    sudo service realmd restart
  else
    # running
    echo "OK"
  fi

  # is it running? ################## mangosd ##################################

  # service running? >
  if sudo service mangosd status &>/dev/null; then
    # running
    echo "OK"
  else
    # offline
    sudo service mangosd restart &>/dev/null
  fi

  # is it connected? ################ mangosd ##################################

  # mangosd mysql gone away >
  if tail "$FOLDER_CORE"/run/logs/Server.log 2>/dev/null |
    grep -m 1 "gone away" 2>/dev/null; then
    # it's gone..
    sudo service mangosd restart
  else
    # running
    echo "OK"
  fi
  # mangosd mysql connection was killed >
  if tail "$FOLDER_CORE"/run/logs/Server.log 2>/dev/null |
    grep -m 1 "Connection was killed" 2>/dev/null; then
    # it's gone..
    sudo service mangosd restart
  else
    # running
    echo "OK"
  fi
  # try to backup regardless ######## characters & realmd ######################

  # backup <- characters.sql
  FILE="$FOLDER_WOW/backup/$DB_CHARACTERS-$NOW.sql"
  if [ ! -f "$FILE" ]; then
    # make new characters backup >
    mysqldump --defaults-extra-file="$SQL_MYCNF" "$DB_CHARACTERS" >"$FOLDER_WOW"/backup/"$DB_CHARACTERS"-"$NOW".sql
    # remove old backup (sql older than 3 days) >
    find "$FOLDER_WOW"/backup/classiccharacters*-*.*.*.sql -mtime +3 -exec rm {} \; &>/dev/null
    # remove old backup inside 'old' directory (sql older than 3 days) >
    find "$FOLDER_WOW"/backup/old/classiccharacters*-*.*.*.sql -mtime +3 -exec rm {} \; &>/dev/null
  else
    echo "OK"
  fi
  # backup <- realmd.sql
  FILE="$FOLDER_WOW/backup/$DB_REALMD-$NOW.sql"
  if [ ! -f "$FILE" ]; then
    # make new realmd backup >
    mysqldump --defaults-extra-file="$SQL_MYCNF" "$DB_REALMD" >"$FOLDER_WOW"/backup/"$DB_REALMD"-"$NOW".sql
    # remove old backup (sql older than 3 days) >
    find "$FOLDER_WOW"/backup/classicrealmd*-*.*.*.sql -mtime +3 -exec rm {} \; &>/dev/null
    # remove old backup inside 'old' directory (sql older than 3 days) >
    find "$FOLDER_WOW"/backup/old/classicrealmd*-*.*.*.sql -mtime +3 -exec rm {} \; &>/dev/null
  else
    echo "OK"
  fi
else
  echo "OK"
fi
